# Inspired by https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

default:
  image: python:3.10

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
  
.base_environment:
  before_script:
    - apt-get update -qy
    - apt-get install -y coinor-cbc git
    - pip install -r requirements.txt

# Make the default stages explicit
stages:
  - linting
  - build
  - test
  - deploy

ruff:
  extends: .base_environment
  stage: linting
  script:
    - pip install ruff
    - ruff check --output-format=gitlab .
  allow_failure: true

pytest:
  extends: .base_environment
  stage: test
  script:
    - pip install pytest 
    - python -m pytest tests
  allow_failure: true

pages:
  stage: build
  script:
    - pip install pdoc
    - pdoc mtress -o ./public
  artifacts:
    paths:
      - public
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
