stages:
  - test
before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - apt-get install -y coinor-cbc
  - pip3 install --upgrade pip
  - pip3 install git+https://github.com/oemof/oemof-thermal.git
  - pip3 install -r requirements.txt
  - pip3 install pytest
test_scripts:
  stage: test
  script:
  - python3 -m pytest tests
pylint:
  stage: test
  image: python:3.7
  script:
    - pip install pylint --quiet
    - pylint meta_model
  allow_failure: true
